/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fees'
    | '/settings'
    | '/sitemap.xml'
    | '/receipts/$id'
    | '/students/$id'
    | '/receipts/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fees'
    | '/settings'
    | '/sitemap.xml'
    | '/receipts/$id'
    | '/students/$id'
    | '/receipts'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/fees'
    | '/settings'
    | '/sitemap.xml'
    | '/receipts/$id'
    | '/students/$id'
    | '/receipts/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeesRoute: typeof FeesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeesRoute: FeesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ReceiptsIdRoute: ReceiptsIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
