/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceiptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRouteWithChildren
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRouteWithChildren
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/receipts': typeof ReceiptsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRouteWithChildren
  '/receipts/$id': typeof ReceiptsIdRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fees'
    | '/receipts'
    | '/settings'
    | '/sitemap.xml'
    | '/students'
    | '/receipts/$id'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fees'
    | '/receipts'
    | '/settings'
    | '/sitemap.xml'
    | '/students'
    | '/receipts/$id'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/fees'
    | '/receipts'
    | '/settings'
    | '/sitemap.xml'
    | '/students'
    | '/receipts/$id'
    | '/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeesRoute: typeof FeesRoute
  ReceiptsRoute: typeof ReceiptsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof ReceiptsRoute
    }
  }
}

interface ReceiptsRouteChildren {
  ReceiptsIdRoute: typeof ReceiptsIdRoute
}

const ReceiptsRouteChildren: ReceiptsRouteChildren = {
  ReceiptsIdRoute: ReceiptsIdRoute,
}

const ReceiptsRouteWithChildren = ReceiptsRoute._addFileChildren(
  ReceiptsRouteChildren,
)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeesRoute: FeesRoute,
  ReceiptsRoute: ReceiptsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
